/*
 * Interrupt_gen_config.h
 *
 * Created: 9/8/2022 1:09:33 AM
 *  Author: ADEL
 */ 


#ifndef INTERRUPT_GEN_CONFIG_H_
#define INTERRUPT_GEN_CONFIG_H_


#define INTERRUPT_FEATURE_DISABLE   0
#define INTERRUPT_FEATURE_ENABLE    1

#define GLOBAL_INTERRUPT_FEATURE_ENABLE        INTERRUPT_FEATURE_ENABLE

#define EXTERNAL_INTERRUPT_FEATURE_ENABLE      INTERRUPT_FEATURE_ENABLE
#define TIMER0_OVERFLOW_INTERRUPT_ENABLE       INTERRUPT_FEATURE_DISABLE
#define TIMER0_OCM_INTERRUPT_ENABLE            INTERRUPT_FEATURE_ENABLE

#define UART_TXC_INTERRUPT_ENABLE              INTERRUPT_FEATURE_ENABLE
#define UART_RXC_INTERRUPT_ENABLE              INTERRUPT_FEATURE_ENABLE
#define UART_UDRE_INTERRUPT_ENABLE             INTERRUPT_FEATURE_DISABLE


#endif /* INTERRUPT_GEN_CONFIG_H_ */